FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# kanzway

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }

## Sale Items Collection [/v1/vendor/saleItems]

### List All Sale Items [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "title": {
                            "en": "SLOTLESS MOTOR",
                            "ar": "محرك بدون فتحات"
                        },
                        "slug": "slotless-motor",
                        "code": "P0123456",
                        "mpn": "A1001.4",
                        "gtin": {
                            "ean": "032323401",
                            "upc": "1234567890"
                        },
                        "familyCode": "FM001",
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "categories": {
                            "en": "Hand Tools / Power Tools / Accessories",
                            "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                        },
                        "brand": {
                            "id": 1,
                            "name": {
                                "en": "Dormer",
                                "ar": "دورمير"
                            },
                            "image": {
                                "id": 1,
                                "name": "dormer",
                                "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        "store": {
                            "id": 1,
                            "name": "ABC Store"
                        },
                        "minPrice": 100,
                        "maxPrice": 200,
                        "discount": 150,
                        "stock": 10,
                        "enabled": true
                    },
                    {
                        "id": 2,
                        "title": {
                            "en": "SLOTLESS MOTOR",
                            "ar": "محرك بدون فتحات"
                        },
                        "slug": "slotless-motor",
                        "code": "P0123456",
                        "mpn": "A1001.4",
                        "gtin": {
                            "ean": "032323401",
                            "upc": "1234567890"
                        },
                        "familyCode": "FM001",
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "categories": {
                            "en": "Hand Tools / Power Tools / Accessories",
                            "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                        },
                        "brand": {
                            "id": 1,
                            "name": {
                                "en": "Dormer",
                                "ar": "دورمير"
                            },
                            "image": {
                                "id": 1,
                                "name": "dormer",
                                "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        "store": {
                            "id": 1,
                            "name": "ABC Store"
                        },
                        "minPrice": null,
                        "maxPrice": null,
                        "discount": null,
                        "stock": null,
                        "enabled": false
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
### Create a New Sale Item [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }

## Sale Item [/v1/vendor/saleItems/{id}]

+ Parameters
    + id (number) - ID of the Sale Item in the form of an integer

### View a Sale Item Detail [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "id": 1,
                "title": {
                    "en": "SLOTLESS MOTOR",
                    "ar": "محرك بدون فتحات"
                },
                "slug": "slotless-motor",
                "code": "P0123456",
                "mpn": "A1001.4",
                "gtin": {
                    "ean": "032323401",
                    "upc": "1234567890"
                },
                "familyCode": "FM001",
                "image": {
                    "id": 1,
                    "name": "dormer-a100-primary-angle2",
                    "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                    "width": 800,
                    "height": 600,
                    "type": "image"
                },
                "categories": {
                    "en": "Hand Tools / Power Tools / Accessories",
                    "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                },
                "brand": {
                    "id": 1,
                    "name": {
                        "en": "Dormer",
                        "ar": "دورمير"
                    },
                    "image": {
                        "id": 1,
                        "name": "dormer",
                        "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                        "width": 800,
                        "height": 600,
                        "type": "image"
                    }
                },
                "store": {
                    "id": 1,
                    "name": "ABC Store"
                },
                "minPrice": 100,
                "maxPrice": 200,
                "discount": 150,
                "stock": 10,
                "description": {
                    "en": "<p>Subland drill with 90° included step angle, straight shank and a drilling-pilot diameter of 8.40mm with a length of 19.00mm, a large diameter of 15.00mm and an overall length of 169mm, according to DIN 8374 standard to produce a close fit through hole and conical seat for M8 countersunk-head screws, HSS and steam tempered finish for machining free machining, plain carbon and alloy steel and grey cast-iron</p>",
                    "ar": "<p>مثقاب أرضي فرعي بزاوية خطوة متضمنة تبلغ 90 درجة، وساق مستقيمة وقطر دليل الحفر 8.40 مم وطول 19.00 مم، وقطر كبير 15.00 مم وطول إجمالي 169 مم، وفقًا لمعيار DIN 8374 لإنتاج توافق قريب من خلال الفتحة والمقعد المخروطي للبراغي ذات الرأس الغاطسة M8، وتشطيب HSS والمعالجة بالبخار للتصنيع الحر، والكربون العادي وسبائك الفولاذ والحديد الزهر الرمادي</p>"
                },
                "metaKeyword": "meta_keyword",
                "metaDescription": "meta_description",
                "galleries": [
                    {
                        "id": 1,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 2,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-secondary-side2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-secondary-side2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 3,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-additional-front2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-additional-front2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 4,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-dimensional-dim",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-dimensional-dim.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    }
                ],
                "properties": [
                    {
                        "name": {
                            "en": "Spesification",
                            "ar": "تخصيص"
                        },
                        "type": "table",
                        "fields": [
                            {
                                "en": "Descriptions",
                                "ar": "الأوصاف"
                            },
                            {
                                "en": "Value 1",
                                "ar": "قيمة"
                            }
                        ],
                        "sequence": 1,
                        "groups": [
                            {
                                "id": 1,
                                "name": {
                                    "en": "Group 1",
                                    "ar": "مجموعة 1"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "description one",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "10",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description two",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description three",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    }
                                ]
                            },
                            {
                                "id": 2,
                                "name": {
                                    "en": "Group 2",
                                    "ar": "مجموعة 2"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "description one",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "10",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description two",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description three",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "name": {
                            "en": "Cutting Conditions",
                            "ar": "شروط القطع"
                        },
                        "type": "table",
                        "fields": [
                            {
                                "en": "Name",
                                "ar": "الأوصاف"
                            },
                            {
                                "en": "Sustainability",
                                "ar": "قيمة"
                            },
                            {
                                "en": "Cutting Speed",
                                "ar": "سرعة"
                            },
                            {
                                "en": "Cutting Feed",
                                "ar": "غير"
                            }
                        ],
                        "sequence": 2,
                        "groups": [
                            {
                                "id": 1,
                                "group": {
                                    "en": "P - Steel and cast steel(steels with alloy content ≤ 10% and a hardness of < 45HRC)",
                                    "ar": "P - الفولاذ والفولاذ المصبوب (الفولاذ الذي يحتوي على سبائك أقل من أو يساوي 10% وصلابة أقل من 45HRC)"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "isActive": true
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
### Delete a Sale Item [DELETE]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }
            
### Update a Sale Item [PUT]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }
            
## Products Collection [/v1/vendor/products]

### List All Products [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "title": {
                            "en": "SLOTLESS MOTOR",
                            "ar": "محرك بدون فتحات"
                        },
                        "slug": "slotless-motor",
                        "code": "P0123456",
                        "mpn": "A1001.4",
                        "gtin": {
                            "ean": "032323401",
                            "upc": "1234567890"
                        },
                        "familyCode": "FM001",
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "categories": {
                            "en": "Hand Tools / Power Tools / Accessories",
                            "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                        },
                        "brand": {
                            "id": 1,
                            "name": {
                                "en": "Dormer",
                                "ar": "دورمير"
                            },
                            "image": {
                                "id": 1,
                                "name": "dormer",
                                "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        "status": "active"
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
### Create a New Product [POST]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }

## Product [/v1/vendor/products/{id}]

+ Parameters
    + id (number) - ID of the Product in the form of an integer

### View a Product Detail [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "id": 1,
                "title": {
                    "en": "SLOTLESS MOTOR",
                    "ar": "محرك بدون فتحات"
                },
                "slug": "slotless-motor",
                "code": "P0123456",
                "mpn": "A1001.4",
                "gtin": {
                    "ean": "032323401",
                    "upc": "1234567890"
                },
                "familyCode": "FM001",
                "image": {
                    "id": 1,
                    "name": "dormer-a100-primary-angle2",
                    "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                    "width": 800,
                    "height": 600,
                    "type": "image"
                },
                "categories": {
                    "en": "Hand Tools / Power Tools / Accessories",
                    "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                },
                "brand": {
                    "id": 1,
                    "name": {
                        "en": "Dormer",
                        "ar": "دورمير"
                    },
                    "image": {
                        "id": 1,
                        "name": "dormer",
                        "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                        "width": 800,
                        "height": 600,
                        "type": "image"
                    }
                },
                "store": {
                    "id": 1,
                    "name": "ABC Store"
                },
                "minPrice": 100,
                "maxPrice": 200,
                "discount": 150,
                "stock": 10,
                "description": {
                    "en": "<p>Subland drill with 90° included step angle, straight shank and a drilling-pilot diameter of 8.40mm with a length of 19.00mm, a large diameter of 15.00mm and an overall length of 169mm, according to DIN 8374 standard to produce a close fit through hole and conical seat for M8 countersunk-head screws, HSS and steam tempered finish for machining free machining, plain carbon and alloy steel and grey cast-iron</p>",
                    "ar": "<p>مثقاب أرضي فرعي بزاوية خطوة متضمنة تبلغ 90 درجة، وساق مستقيمة وقطر دليل الحفر 8.40 مم وطول 19.00 مم، وقطر كبير 15.00 مم وطول إجمالي 169 مم، وفقًا لمعيار DIN 8374 لإنتاج توافق قريب من خلال الفتحة والمقعد المخروطي للبراغي ذات الرأس الغاطسة M8، وتشطيب HSS والمعالجة بالبخار للتصنيع الحر، والكربون العادي وسبائك الفولاذ والحديد الزهر الرمادي</p>"
                },
                "metaKeyword": "meta_keyword",
                "metaDescription": "meta_description",
                "galleries": [
                    {
                        "id": 1,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 2,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-secondary-side2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-secondary-side2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 3,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-additional-front2",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-additional-front2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    {
                        "id": 4,
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-dimensional-dim",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-dimensional-dim.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    }
                ],
                "properties": [
                    {
                        "name": {
                            "en": "Spesification",
                            "ar": "تخصيص"
                        },
                        "type": "table",
                        "fields": [
                            {
                                "en": "Descriptions",
                                "ar": "الأوصاف"
                            },
                            {
                                "en": "Value 1",
                                "ar": "قيمة"
                            }
                        ],
                        "sequence": 1,
                        "groups": [
                            {
                                "id": 1,
                                "name": {
                                    "en": "Group 1",
                                    "ar": "مجموعة 1"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "description one",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "10",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description two",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description three",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    }
                                ]
                            },
                            {
                                "id": 2,
                                "name": {
                                    "en": "Group 2",
                                    "ar": "مجموعة 2"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "description one",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "10",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description two",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "description three",
                                            "ar": "وصف واحد"
                                        },
                                        "value1": {
                                            "en": "11",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "value2": null,
                                        "valueUnit2": null,
                                        "value3": null,
                                        "valueUnit3": null,
                                        "icon": ""
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "name": {
                            "en": "Cutting Conditions",
                            "ar": "شروط القطع"
                        },
                        "type": "table",
                        "fields": [
                            {
                                "en": "Name",
                                "ar": "الأوصاف"
                            },
                            {
                                "en": "Sustainability",
                                "ar": "قيمة"
                            },
                            {
                                "en": "Cutting Speed",
                                "ar": "سرعة"
                            },
                            {
                                "en": "Cutting Feed",
                                "ar": "غير"
                            }
                        ],
                        "sequence": 2,
                        "groups": [
                            {
                                "id": 1,
                                "group": {
                                    "en": "P - Steel and cast steel(steels with alloy content ≤ 10% and a hardness of < 45HRC)",
                                    "ar": "P - الفولاذ والفولاذ المصبوب (الفولاذ الذي يحتوي على سبائك أقل من أو يساوي 10% وصلابة أقل من 45HRC)"
                                },
                                "items": [
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    },
                                    {
                                        "description": {
                                            "en": "P1.1 - Free machining sulfurized carbon steel with a hardness of < 240HB",
                                            "ar": "P1.1 - تصنيع مجاني للفولاذ الكربوني المكبرت بصلابة أقل من 240HB"
                                        },
                                        "value1": {
                                            "en": "Primary Use",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit1": {
                                            "en": "",
                                            "ar": ""
                                        },
                                        "value2": {
                                            "en": "95",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit2": {
                                            "en": "ft/min",
                                            "ar": "سم"
                                        },
                                        "value3": {
                                            "en": "0.00065",
                                            "ar": "ساتو"
                                        },
                                        "valueUnit3": {
                                            "en": "cm",
                                            "ar": "سم"
                                        },
                                        "icon": ""
                                    }
                                ]
                            }
                        ]
                    }
                ],
                "isActive": true
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
### Delete a Product [DELETE]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }
            
### Update a Product [PUT]

+ Request (application/json)

        {

        }

+ Response 201 (application/json)

    + Body

            {
                "code": 0,
                "message": null,
                "data": {},
                "timestamp": "2024-01-25 10:10:10"
            }

## Reviews Collection [/v1/reviews]

### List All Reviews [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "title": {
                            "en": "Jobber Drill Diameter 0.413 inch",
                            "ar": "بدون اسم 1"
                        },
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2.png",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "date": "2024-03-07 10:10:10",
                        "avgRating": 5,
                        "totalRating": 121,
                        "totalReview": 1000
                    },
                    {
                        "id": 2,
                        "title": {
                            "en": "Jobber Drill Diameter 0.413 inch",
                            "ar": "بدون اسم 1"
                        },
                        "image": {
                            "id": 1,
                            "name": "dormer-a100-primary-angle2.png",
                            "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "date": "2024-03-07 10:10:10",
                        "avgRating": 4,
                        "totalRating": 91,
                        "totalReview": 900
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }

## Reviews [/v1/vendor/reviews/{id}]

+ Parameters
    + id (number) - ID of the Product in the form of an integer

### View a Reviews Detail [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "product": {
                    "title": {
                        "en": "Jobber Drill Diameter 0.413 inch",
                        "ar": "بدون اسم 1"
                    },
                    "code": "P0123456",
                    "mpn": "A100Z",
                    "gtin": {
                        "ean": "7320760029619",
                        "upc": "73207600296"
                    },
                    "categories": {
                        "en": "Hand Tools / Power Tools / Accessories",
                        "ar": "أدوات القياس / نسشتيا  ظ مشسنيتم "
                    },
                    "brand": {
                        "id": 1,
                        "name": {
                            "en": "Dormer",
                            "ar": "دورمير"
                        },
                        "image": {
                            "id": 1,
                            "name": "dormer",
                            "url": "https://kanzway.com:3465/v1//images/download/L14461.gif",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        }
                    },
                    "galleries": [
                        {
                            "id": 1,
                            "image": {
                                "id": 1,
                                "name": "dormer-a100-primary-angle2",
                                "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-primary-angle2.png",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        {
                            "id": 2,
                            "image": {
                                "id": 1,
                                "name": "dormer-a100-secondary-side2",
                                "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-secondary-side2.png",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        {
                            "id": 3,
                            "image": {
                                "id": 1,
                                "name": "dormer-a100-additional-front2",
                                "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-additional-front2.png",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        },
                        {
                            "id": 4,
                            "image": {
                                "id": 1,
                                "name": "dormer-a100-dimensional-dim",
                                "url": "https://kanzway.com:3465/v1/images/download/dormer-a100-dimensional-dim.png",
                                "width": 800,
                                "height": 600,
                                "type": "image"
                            }
                        }
                    ]
                },
                "reviews": {
                    "summary": {
                        "avgRating": 4,
                        "totalRating": 100,
                        "totalReview": 1000,
                        "star_1": 0,
                        "star_2": 5,
                        "star_3": 10,
                        "star_4": 10,
                        "star_5": 30
                    },
                    "page": 1,
                    "size": 10,
                    "count": 2,
                    "totalCount": 12,
                    "content": [
                        {
                            "id": 1,
                            "date": "2024-01-24",
                            "principal": {
                                "firstName": "Darrell",
                                "lastName": "Steward",
                                "profilePicture": "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg"
                            },
                            "rating": 4,
                            "comment": "The product is exactly as described – excellent quality, swift delivery, and the online shopping experience was a breeze. Kudos to the team for top-notch service!",
                            "images": [
                                "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg",
                                "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg"
                            ],
                            "orderCode": "#INV-98849",
                            "price": 2000
                        },
                        {
                            "id": 2,
                            "date": "2024-01-24",
                            "principal": {
                                "firstName": "Darrell",
                                "lastName": "Steward",
                                "profilePicture": "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg"
                            },
                            "rating": 4,
                            "comment": "The product is exactly as described – excellent quality, swift delivery, and the online shopping experience was a breeze. Kudos to the team for top-notch service!",
                            "images": [
                                "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg",
                                "https://www.demoapp.xyz/kanzway/html/img/review-1.jpg"
                            ],
                            "orderCode": "#INV-98849",
                            "price": 2000
                        }
                    ]
                }
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
## Brand Collection [/v1/admin/brands]

### List All Reviews [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "name": {
                            "en": "Baluff",
                            "ar": "بالوف"
                        },
                        "slug": "baluff",
                        "image": {
                            "id": 1,
                            "name": "Baluff",
                            "url": "https://www.kanzway.sa:3465/img/list-1.jpg",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "bwImage": {
                            "id": 1,
                            "name": "Baluff",
                            "url": "https://www.kanzway.sa:3465/img/list-1.jpg",
                            "width": 800,
                            "height": 600,
                            "type": "image"
                        },
                        "description": {
                            "en": "lorem ipsum lorem ipsum lorem ipsum",
                            "ar": "أدوات القياس"
                        },
                        "showHomepage": true,
                        "status": "active"
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
## Attributes Collection [/v1/admin/attributes]

### List All Attributes [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "code": "001",
                        "group": {
                            "en": "Length",
                            "ar": "بالوف"
                        },
                        "name": {
                            "en": "Length",
                            "ar": "بالوف"
                        },
                        "unit1": {
                            "en": "cm",
                            "ar": "بالوف"
                        },
                        "unit2": {
                            "en": "",
                            "ar": ""
                        },
                        "unit3": {
                            "en": "",
                            "ar": ""
                        }
                    },
                    {
                        "id": 2,
                        "code": "001",
                        "group": {
                            "en": "Width",
                            "ar": "بالوف"
                        },
                        "name": {
                            "en": "Width",
                            "ar": "بالوف"
                        },
                        "unit1": {
                            "en": "cm",
                            "ar": "بالوف"
                        },
                        "unit2": {
                            "en": "dm",
                            "ar": "بالوف"
                        },
                        "unit3": {
                            "en": "",
                            "ar": ""
                        }
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }
        
## Store Collection [/v1/vendor/stores]

### List All Store [GET]

+ Response 200 (application/json)

        {
            "code": 0,
            "message": null,
            "data": {
                "page": 1,
                "size": 10,
                "count": 2,
                "totalCount": 12,
                "content": [
                    {
                        "id": 1,
                        "code": "001",
                        "name": "ABC Store",
                        "address": "Jalan ABC No 1 Bandung",
                        "city": "Bandung",
                        "country": "Indonesia",
                        "long": "8837455",
                        "lat": "488444"
                    }
                ]
            },
            "timestamp": "2024-01-25 10:10:10"
        }